### ISSUE TITLE
My Page

### ISSUE THREAD

**Issue by pacokwon** [sparcs-kaist/zabo-front-reactjs#22]
Implement MyPage

**Comment by jungdj** [comment]
MyPage개발은 Profile Page 개발로 대체되었습니다.

**Comment by jungdj** [comment]
#26 
On development

**Comment by jungdj** [comment]
- [x] User Profile
- [x] Group Profile

- [x] User Profile Edit
- [x] [User] Profile Image Edit
- [x] [User] Background Photo Edit
- [x] [User] Description Edit
- [x] [User] Username Edit (long term issue)

- [x] Group Profile Edit
- [x] [Group] Profile Image Edit
- [x] [Group] Background Photo Edit
- [x] [Group] Description Edit
- [x] [Group] Group Name Edit (long term issue)

**Comment by Choiyounseo** [comment]
#27

**Comment by Choiyounseo** [comment]
#54 
Temporary group profile page created

**Comment by jungdj** [comment]
끝
